services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    volumes:
      - ./configs:/appdata/configs
      - ./icons:/appdata/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - "7575:7575"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    network_mode: "host"
    volumes:
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/cache:/cache
      - ./services/jellyfin/media:/data/movies
    restart: unless-stopped
