network:
  version: 2
  renderer: networkd
  wifis:
    wlo1:
      dhcp4: no
      addresses:
        - 192.168.1.XX/24  # Replace with your desired Static IP
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
        - to: default
          via: 192.168.1.1
      access-points:
        "YOUR_SSID":
          password: "YOUR_PASSWORD"
