network:
  version: 2
  renderer: networkd
  wifis:
    wlo1:
      dhcp4: no
      addresses:
        - 192.168.1.34/24
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
        - to: default
          via: 192.168.1.1
      access-points:
        "REDACTED_SSID":
          password: "REDACTED_PASSWORD"
